name: pokemon_app
description: Pokemon with list and detail
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  get_it: ^4.0.2
  equatable: ^1.2.2
  provider: ^3.2.0
  palette_generator: ^0.2.2
  flutter_svg: ^0.17.4
  cached_network_image: ^2.0.0
  percent_indicator: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/proxima_bold.otf
          weight: 600
        - asset: fonts/proxima_regular.otf
